### ISSUE TITLE
Custom github endpoint?

### ISSUE THREAD

**Issue by factoidforrest** [steinfletcher/github-team-clone#1]
My companies github api endpoint is not the standard one, is it configurable?

**Comment by steinfletcher** [comment]
Hi @light24bulbs. That would make a nice feature. We hard code the api endpoint in code. It could be passed either as an env var or arg - following the existing pattern for api token.

I don't have a way of testing it and I am not sure if the enterprise API has the same contract as the public API. I'd be grateful if you can check that and submit a PR :)

**Comment by steinfletcher** [comment]
Implemented in v0.2.0 f657b48abb6d9c298743be5ad073c780dc60df3c
